# Generated by Django 6.0 on 2026-01-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='mobile',
            new_name='phone',
        ),
    ]
