# Generated by Django 6.0 on 2026-01-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
