# Generated by Django 6.0 on 2026-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('arts', 'Arts'), ('biology', 'Biology'), ('maths', 'Maths'), ('agriculture', 'Agriculture')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_class',
            field=models.CharField(choices=[('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=10),
        ),
    ]
